---
# Here to set up the Form
Form:
  # Here to set up 'true' or 'false' button
  Button: 
    # Button to Change Name
    nick: true
    # Button Flying Player
    flying: true
    # Button Hide Player
    sizeplayer: true
    # Button set Gamemode
    gamemode: true
    
# Reset Fitur if player Join
Reset:
  nick: true
  flying: true
  sizeplayer: true
  gamemode: true # reset gamemode in Survival mode
...
